Init
p1nkun1c0rns/commitlinter-github-action pull request #1
Opened 2020-04-28 13:55 UTC by steinbrueckri

2020-04-29 12:36 UTC, heubeck approved these changes

2020-06-02 09:54 UTC, kunzese requested changes

2020-06-02 09:54 UTC, kunzese commented on README.md
> +## useage
```suggestion
## usage
```

2020-06-02 09:57 UTC, stuebingerb commented on README.md
> +## useage
```suggestion
## Usage
```

:)

2020-10-29 13:20 UTC, kunzese commented
@steinbrueckri: do you still need this PR?

2020-10-29 15:31 UTC, closed without merging